# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
