# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-06 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('market_capital', models.FloatField()),
                ('sector', models.CharField(max_length=500)),
                ('industry', models.CharField(max_length=1000)),
            ],
        ),
    ]
